# Generated by Django 5.1.6 on 2025-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="register",
            name="Password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="register",
            name="UserName",
            field=models.CharField(max_length=200),
        ),
    ]
