# Generated by Django 5.1.6 on 2025-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_register_email_alter_register_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="myform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Uname", models.CharField(default="", max_length=150)),
                ("Email", models.CharField(default="", max_length=150)),
                ("Password", models.CharField(default="", max_length=150)),
            ],
        ),
    ]
