# Generated by Django 5.1.6 on 2025-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_myform_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Password",
            field=models.CharField(max_length=255),
        ),
    ]
